In [2]:
import numpy as np

In [3]:
# SIMD

In [4]:
# bytecodes

2**10

1024

In [5]:
2**20

1048576

In [6]:
# Processor feature - numpy use -> SIMD

In [7]:
# vecotorization

In [8]:
# ndarray

In [9]:
# borough

In [10]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [15]:
taxi = np.genfromtxt("nyc_taxis.csv",skip_header = True, delimiter = ",")

In [16]:
type(taxi)

numpy.ndarray

In [17]:
taxi.ndim

2

In [18]:
len(taxi)

89560

In [19]:
taxi.shape

(89560, 15)

In [20]:
taxi.dtype

dtype('float64')

In [23]:
# 64 bits -> 8 bytes

# 1 byte - 8 bits

In [24]:
# (89560*15*8)/2**20

In [25]:
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [26]:
89560*15

1343400

In [27]:
taxi[0]

array([2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [28]:
# 10**3

In [29]:
taxi[0][3]

5.0

In [30]:
taxi[0,3]

5.0

In [31]:
# taxi[row, col]
taxi[0:5,:]

array([[2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
        1.165e+01, 6.999e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        1.000e+00, 1.629e+01, 1.520e+03, 4.500e+01, 1.300e+00, 0.000e+00,
        8.000e+00, 5.430e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 1.270e+01, 1.462e+03, 3.650e+01, 1.300e+00, 0.000e+00,
        0.000e+00, 3.780e+01, 2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 8.700e+00, 1.210e+03, 2.600e+01, 1.300e+00, 0.000e+00,
        5.460e+00, 3.276e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 5.560e+00, 7.590e+02, 1.750e+01, 1.300e+00, 0.000e+00,
        0.000e+00, 1.880e+01, 2.000e+00]])

In [33]:
frfc = taxi[0,0]

In [34]:
frfc 

2016.0

In [35]:
frfc = 2017

In [36]:
taxi[0:5,:]

array([[2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
        1.165e+01, 6.999e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        1.000e+00, 1.629e+01, 1.520e+03, 4.500e+01, 1.300e+00, 0.000e+00,
        8.000e+00, 5.430e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 1.270e+01, 1.462e+03, 3.650e+01, 1.300e+00, 0.000e+00,
        0.000e+00, 3.780e+01, 2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 8.700e+00, 1.210e+03, 2.600e+01, 1.300e+00, 0.000e+00,
        5.460e+00, 3.276e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 5.560e+00, 7.590e+02, 1.750e+01, 1.300e+00, 0.000e+00,
        0.000e+00, 1.880e+01, 2.000e+00]])

In [37]:
fr = taxi[0]

In [39]:
fr[0] = 2017

In [40]:
fr

array([2.017e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [41]:
taxi[0:5,:]

array([[2.017e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
        1.165e+01, 6.999e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        1.000e+00, 1.629e+01, 1.520e+03, 4.500e+01, 1.300e+00, 0.000e+00,
        8.000e+00, 5.430e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 1.270e+01, 1.462e+03, 3.650e+01, 1.300e+00, 0.000e+00,
        0.000e+00, 3.780e+01, 2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 8.700e+00, 1.210e+03, 2.600e+01, 1.300e+00, 0.000e+00,
        5.460e+00, 3.276e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 5.560e+00, 7.590e+02, 1.750e+01, 1.300e+00, 0.000e+00,
        0.000e+00, 1.880e+01, 2.000e+00]])

In [ ]:
# list -> slicing -> copy -> wont change original
# array -> slicing -> view -> change original

In [42]:
fr[0] = 2016

In [43]:
taxi[0]

array([2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [44]:
fr = taxi[0].copy()

In [46]:
fr[0] = 2017

In [47]:
taxi[0]

array([2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [48]:
taxi.shape

(89560, 15)

In [49]:
fr

array([2.017e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [50]:
[2.017e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00] +1 

TypeError: can only concatenate list (not "int") to list

In [51]:
fr + 1

array([2.018e+03, 2.000e+00, 2.000e+00, 6.000e+00, 1.000e+00, 3.000e+00,
       5.000e+00, 2.200e+01, 2.038e+03, 5.300e+01, 1.800e+00, 6.540e+00,
       1.265e+01, 7.099e+01, 2.000e+00])

In [54]:
fare = taxi[:,9]

In [55]:
fee = taxi[:,10]

In [56]:
fare 

array([52. , 45. , 36.5, ..., 52. , 34.5, 48. ])

In [57]:
fee

array([0.8, 1.3, 1.3, ..., 0.8, 1.3, 1.3])

In [58]:
fare + fee -> ndarray - 1darray

array([52.8, 46.3, 37.8, ..., 52.8, 35.8, 49.3])

In [59]:
fare.ndim

1

In [60]:
# Maths, stats and economics -> ICMA -CIMA - Datascience/Data Engineering

In [ ]:
# +,-,/,*

In [ ]:
# ndarray -> taxi -> 2darray

In [62]:
taxi.max()

86383.0

In [69]:
taxi[:5,:5]

array([[2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00]])

In [68]:
taxi.shape

(89560, 15)

In [ ]:
# horizontal- row - axis = 1, axis = "columns"
# Vertical- column - axis = 0, axis = "index"


# .
# .
# .
# .
# . . . . . . . 

In [70]:
taxi[:5,:5].max(axis = 1) # rowwise

array([2016., 2016., 2016., 2016., 2016.])

In [71]:
taxi[:5,:5].max(axis = 0) # columwise

array([2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00])

# numpy methods

* max()
* min()
* sum()
* mean()

In [72]:
tot_amt = taxi[:,13]

In [73]:
tot_amt

array([69.99, 54.3 , 37.8 , ..., 63.34, 44.75, 54.84])

In [75]:
taxi[:,9:13].sum(axis = 1)

array([69.99, 54.3 , 37.8 , ..., 63.34, 44.75, 54.84])

In [76]:
taxi[:,9] + taxi[:,10] + taxi[:,11] + taxi[:,12]

array([69.99, 54.3 , 37.8 , ..., 63.34, 44.75, 54.84])

In [80]:
# list(taxi)
lst = taxi.tolist()

In [77]:
import time

In [83]:
start_arr = time.time()
t_am_arr = taxi[:,9:13].sum(axis = 1)
end_arr = time.time()

In [84]:
start_lst = time.time()

t_am_lst = []
for row in lst:
    amt = row[9] + row[10] + row[11] + row[12]
    t_am_lst.append(amt)

end_lst = time.time()

In [85]:
end_arr - start_arr

0.004003763198852539

In [86]:
end_lst- start_lst

0.22793817520141602

In [87]:
print(t_am_arr[:3])

[69.99 54.3  37.8 ]


In [88]:
print(t_am_lst[:3])

[69.99, 54.3, 37.8]


In [89]:
time.time()

1645350425.0707686

In [90]:
# broadcasting

In [91]:
arr1 = np.array([1,2,3])
arr2 = np.array([[5],
                 [4],
                 [3]])

In [92]:
arr1

array([1, 2, 3])

In [93]:
arr2

array([[5],
       [4],
       [3]])

In [94]:
arr1.shape

(3,)

In [96]:
arr2.shape

(3, 1)

In [97]:
arr1 + arr2

array([[6, 7, 8],
       [5, 6, 7],
       [4, 5, 6]])

In [98]:
# array([1, 2, 3]) + array([[5],
#                           [4],
#                           [3]])


# [1, 2, 3] + [5, 5, 5]
# [1, 2, 3] + [4, 4 , 4]
# [1, 2, 3] + [3, 3 , 3]

In [99]:
# (3,)  (3, 1)


# (1,3)  (3, 1)

# (3,3), (3, 3)

In [100]:
arr3 = np.array([2,3])

In [103]:
arr2 + arr3

array([[7, 8],
       [6, 7],
       [5, 6]])

In [101]:
arr3.shape

(2,)

In [102]:
arr2.shape

(3, 1)

In [ ]:
(3, 1)   (2,)

(3, 1)   (1,2)

(3, 2)   (3,2)

In [104]:
arr4 = np.array([[2,3],
                [4,5]])

In [105]:
arr4.shape

(2, 2)

In [106]:
arr2.shape

(3, 1)

In [107]:
arr2 + arr4

ValueError: operands could not be broadcast together with shapes (3,1) (2,2) 

In [108]:
# (3,1) (2,2)

# (3,2) (2,2)

In [109]:
arr4

array([[2, 3],
       [4, 5]])

In [110]:
arr4.reshape(4,)

array([2, 3, 4, 5])

In [111]:
arr4.reshape((4,1))

array([[2],
       [3],
       [4],
       [5]])

In [112]:
arr4.reshape((3,1))

ValueError: cannot reshape array of size 4 into shape (3,1)

In [113]:
arr4.reshape((2,2))

array([[2, 3],
       [4, 5]])

In [116]:
arr4.reshape((2,2))

array([[2, 3],
       [4, 5]])

In [117]:
arr4.reshape((2,2), order = "F")

array([[2, 3],
       [4, 5]])

In [120]:
a = np.array([2,3,
 4,5])

In [121]:
a.reshape((2,2))

array([[2, 3],
       [4, 5]])

In [122]:
a.reshape((2,2), order = "F")

array([[2, 4],
       [3, 5]])

In [124]:
r = np.array(range(1,9))

In [125]:
r

array([1, 2, 3, 4, 5, 6, 7, 8])

In [126]:
r.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])