In [1]:
import numpy as np

In [2]:
taxi = np.genfromtxt("nyc_taxis.csv",
                     delimiter = ",")

In [3]:
taxi.shape

(89561, 15)

In [4]:
taxi.dtype

dtype('float64')

In [8]:
# dir(np)

np.set_printoptions(suppress = True)

In [9]:
taxi

array([[    nan,     nan,     nan, ...,     nan,     nan,     nan],
       [2016.  ,    1.  ,    1.  , ...,   11.65,   69.99,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    8.  ,   54.3 ,    1.  ],
       ...,
       [2016.  ,    6.  ,   30.  , ...,    5.  ,   63.34,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    8.95,   44.75,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    0.  ,   54.84,    2.  ]])

In [10]:
# "Waqas"

In [12]:
# None 
# commercial solution
# product - APis
# Publication

In [11]:
# ISP -> Idependent Study Project 

In [13]:
wn = np.genfromtxt("nyc_taxis.csv",
                     delimiter = ",", names = True)

In [14]:
wn

array([(2016., 1.,  1., 5., 0., 2., 4., 21.  , 2037., 52. , 0.8, 5.54, 11.65, 69.99, 1.),
       (2016., 1.,  1., 5., 0., 2., 1., 16.29, 1520., 45. , 1.3, 0.  ,  8.  , 54.3 , 1.),
       (2016., 1.,  1., 5., 0., 2., 6., 12.7 , 1462., 36.5, 1.3, 0.  ,  0.  , 37.8 , 2.),
       ...,
       (2016., 6., 30., 4., 5., 2., 4., 17.48, 2822., 52. , 0.8, 5.54,  5.  , 63.34, 1.),
       (2016., 6., 30., 4., 5., 2., 6., 12.76, 1083., 34.5, 1.3, 0.  ,  8.95, 44.75, 1.),
       (2016., 6., 30., 4., 5., 2., 0., 17.54, 1711., 48. , 1.3, 5.54,  0.  , 54.84, 2.)],
      dtype=[('pickup_year', '<f8'), ('pickup_month', '<f8'), ('pickup_day', '<f8'), ('pickup_dayofweek', '<f8'), ('pickup_time', '<f8'), ('pickup_location_code', '<f8'), ('dropoff_location_code', '<f8'), ('trip_distance', '<f8'), ('trip_length', '<f8'), ('fare_amount', '<f8'), ('fees_amount', '<f8'), ('tolls_amount', '<f8'), ('tip_amount', '<f8'), ('total_amount', '<f8'), ('payment_type', '<f8')])

In [52]:
wn.shape

(89560,)

In [15]:
wn.dtype

dtype([('pickup_year', '<f8'), ('pickup_month', '<f8'), ('pickup_day', '<f8'), ('pickup_dayofweek', '<f8'), ('pickup_time', '<f8'), ('pickup_location_code', '<f8'), ('dropoff_location_code', '<f8'), ('trip_distance', '<f8'), ('trip_length', '<f8'), ('fare_amount', '<f8'), ('fees_amount', '<f8'), ('tolls_amount', '<f8'), ('tip_amount', '<f8'), ('total_amount', '<f8'), ('payment_type', '<f8')])

In [16]:
wn['pickup_year']

array([2016., 2016., 2016., ..., 2016., 2016., 2016.])

In [17]:
wn['trip_distance']

array([21.  , 16.29, 12.7 , ..., 17.48, 12.76, 17.54])

In [18]:
wn[['pickup_year','trip_distance']]

array([(2016., 21.  ), (2016., 16.29), (2016., 12.7 ), ...,
       (2016., 17.48), (2016., 12.76), (2016., 17.54)],
      dtype={'names':['pickup_year','trip_distance'], 'formats':['<f8','<f8'], 'offsets':[0,56], 'itemsize':120})

In [20]:
taxi = taxi[1:]

In [21]:
taxi

array([[2016.  ,    1.  ,    1.  , ...,   11.65,   69.99,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    8.  ,   54.3 ,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    0.  ,   37.8 ,    2.  ],
       ...,
       [2016.  ,    6.  ,   30.  , ...,    5.  ,   63.34,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    8.95,   44.75,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    0.  ,   54.84,    2.  ]])

In [22]:
taxi = np.genfromtxt("nyc_taxis.csv", delimiter = ",", skip_header = True)

In [23]:
taxi

array([[2016.  ,    1.  ,    1.  , ...,   11.65,   69.99,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    8.  ,   54.3 ,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    0.  ,   37.8 ,    2.  ],
       ...,
       [2016.  ,    6.  ,   30.  , ...,    5.  ,   63.34,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    8.95,   44.75,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    0.  ,   54.84,    2.  ]])

In [24]:
taxi = np.genfromtxt("nyc_taxis.csv", delimiter = ",", skip_header = 1)

In [27]:
# Boolean array -> boolean values -> True, False -> 1,0
# boolean vector
# boolean mask

In [28]:
# Boolean array act as filter

In [29]:
taxi[:,1]

array([1., 1., 1., ..., 6., 6., 6.])

In [31]:
bol = taxi[:,1] == 2.

In [32]:
bol

array([False, False, False, ..., False, False, False])

In [33]:
taxi[bol] # boolean indexing -SIMD

array([[2016.  ,    2.  ,    1.  , ...,    0.  ,   33.34,    2.  ],
       [2016.  ,    2.  ,    1.  , ...,    2.  ,   14.8 ,    1.  ],
       [2016.  ,    2.  ,    1.  , ...,    6.35,   38.15,    1.  ],
       ...,
       [2016.  ,    2.  ,   29.  , ...,    0.  ,   52.8 ,    2.  ],
       [2016.  ,    2.  ,   29.  , ...,    6.35,   38.19,    1.  ],
       [2016.  ,    2.  ,   29.  , ...,    3.  ,   26.3 ,    1.  ]])

In [34]:
taxi[bol].shape

(13333, 15)

In [35]:
taxi[:, -3]

array([11.65,  8.  ,  0.  , ...,  5.  ,  8.95,  0.  ])

In [36]:
taxi[:, 12]

array([11.65,  8.  ,  0.  , ...,  5.  ,  8.95,  0.  ])

In [42]:
bol1 = taxi[:, -3] > 50

bol1

array([False, False, False, ..., False, False, False])

In [38]:
taxi[bol1]

array([[ 2016.  ,     1.  ,     1.  ,     5.  ,     0.  ,     4.  ,
            2.  ,    21.45,  2004.  ,    52.  ,     0.8 ,     0.  ,
           52.8 ,   105.6 ,     1.  ],
       [ 2016.  ,     1.  ,    11.  ,     1.  ,     0.  ,     3.  ,
            4.  ,     9.2 ,  1041.  ,    27.  ,     1.3 ,     5.54,
           60.  ,    93.84,     1.  ],
       [ 2016.  ,     1.  ,    27.  ,     3.  ,     5.  ,     2.  ,
            0.  ,    19.8 ,  1671.  ,    52.5 ,     1.3 ,     5.54,
           59.34,   118.68,     1.  ],
       [ 2016.  ,     2.  ,    19.  ,     5.  ,     2.  ,     4.  ,
            2.  ,    18.42,  2968.  ,    52.  ,     0.8 ,     5.54,
           80.  ,   138.34,     1.  ],
       [ 2016.  ,     3.  ,     9.  ,     3.  ,     4.  ,     3.  ,
            6.  ,     0.49,   158.  ,     3.5 ,     1.8 ,     0.  ,
           70.  ,    75.3 ,     1.  ],
       [ 2016.  ,     3.  ,    17.  ,     4.  ,     1.  ,     2.  ,
            2.  ,     2.7 ,   381.  ,     9.5 ,     0.8 ,

In [40]:
taxi[bol1, 5:13]

array([[    4.  ,     2.  ,    21.45,  2004.  ,    52.  ,     0.8 ,
            0.  ,    52.8 ],
       [    3.  ,     4.  ,     9.2 ,  1041.  ,    27.  ,     1.3 ,
            5.54,    60.  ],
       [    2.  ,     0.  ,    19.8 ,  1671.  ,    52.5 ,     1.3 ,
            5.54,    59.34],
       [    4.  ,     2.  ,    18.42,  2968.  ,    52.  ,     0.8 ,
            5.54,    80.  ],
       [    3.  ,     6.  ,     0.49,   158.  ,     3.5 ,     1.8 ,
            0.  ,    70.  ],
       [    2.  ,     2.  ,     2.7 ,   381.  ,     9.5 ,     0.8 ,
            0.  ,    60.  ],
       [    3.  ,     4.  ,     9.54,  1210.  ,    27.5 ,     0.8 ,
            5.54,    55.  ],
       [    2.  ,     4.  ,    17.6 ,  3251.  ,    52.  ,     0.8 ,
            5.54,    65.  ],
       [    4.  ,     2.  ,    38.2 ,  9252.  ,    52.  ,     0.8 ,
            5.54,    80.  ],
       [    4.  ,     2.  ,    18.  ,  2276.  ,     0.01,     0.3 ,
            5.54,    62.  ],
       [    2.  ,     0.  ,   

In [41]:
taxi[bol1, 12]

array([ 52.8 ,  60.  ,  59.34,  80.  ,  70.  ,  60.  ,  55.  ,  65.  ,
        80.  ,  62.  , 100.  ,  58.  ,  62.  ,  75.7 ,  60.  ,  70.  ])

In [43]:
# e+2

# and or not -> python logical operator

# &   |   ~   -> Numpy logical operator


In [44]:
taxi[~ bol1, 12]

array([11.65,  8.  ,  0.  , ...,  5.  ,  8.95,  0.  ])

In [47]:
# print(taxi[~ bol1, 12].tolist())

In [48]:
# 2% 

taxi[~ bol1, 12] = 0

In [49]:
taxi

array([[2016.  ,    1.  ,    1.  , ...,    0.  ,   69.99,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    0.  ,   54.3 ,    1.  ],
       [2016.  ,    1.  ,    1.  , ...,    0.  ,   37.8 ,    2.  ],
       ...,
       [2016.  ,    6.  ,   30.  , ...,    0.  ,   63.34,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    0.  ,   44.75,    1.  ],
       [2016.  ,    6.  ,   30.  , ...,    0.  ,   54.84,    2.  ]])

In [50]:
taxi[bol1, 12]

array([ 52.8 ,  60.  ,  59.34,  80.  ,  70.  ,  60.  ,  55.  ,  65.  ,
        80.  ,  62.  , 100.  ,  58.  ,  62.  ,  75.7 ,  60.  ,  70.  ])

In [51]:
# fortune 500

In [53]:
# Limitation

# Pandas 

In [55]:
# DataFrame - 2darray -> list of lists
# Series - 1darray -> list 

In [56]:
# rows -> index -> axis = 0
# columns -> columns -> axis = 1

In [57]:
import pandas as pd

In [58]:
f500 = pd.read_csv("f500.csv")

In [59]:
f500

company  rank  revenues  revenue_change  profits  \
0                           Walmart     1    485873             0.8  13643.0   
1                        State Grid     2    315199            -4.4   9571.3   
2                     Sinopec Group     3    267518            -9.1   1257.9   
3          China National Petroleum     4    262573           -12.3   1867.5   
4                      Toyota Motor     5    254694             7.7  16899.3   
..                              ...   ...       ...             ...      ...   
495  Teva Pharmaceutical Industries   496     21903            11.5    329.0   
496        New China Life Insurance   497     21796           -13.3    743.9   
497       Wm. Morrison Supermarkets   498     21741           -11.3    406.4   
498                             TUI   499     21655            -5.5   1151.7   
499                      AutoNation   500     21609             3.6    430.5   

     assets  profit_change                  ceo  \
0    198825           -7.2  C. Douglas McMillon   
1    489838           -6.2              Kou Wei   
2    310726          -65.0            Wang Yupu   
3    585619          -73.7        Zhang Jianhua   
4    437575          -12.3          Akio Toyoda   
..      ...            ...                  ...   
495   92890          -79.3    Yitzhak Peterburg   
496  100609          -45.6             Wan Feng   
497   11630           20.4       David T. Potts   
498   16247          195.5    Friedrich Joussen   
499   10060           -2.7   Michael J. Jackson   

                            industry                  sector  previous_rank  \
0              General Merchandisers               Retailing              1   
1                          Utilities                  Energy              2   
2                 Petroleum Refining                  Energy              4   
3                 Petroleum Refining                  Energy              3   
4           Motor Vehicles and Parts  Motor Vehicles & Parts              8   
..                               ...                     ...            ...   
495                  Pharmaceuticals             Health Care              0   
496  Insurance: Life, Health (stock)              Financials            427   
497             Food and Drug Stores      Food & Drug Stores            437   
498                  Travel Services       Business Services            467   
499              Specialty Retailers               Retailing              0   

     country           hq_location                       website  \
0        USA       Bentonville, AR        http://www.walmart.com   
1      China        Beijing, China        http://www.sgcc.com.cn   
2      China        Beijing, China        http://www.sinopec.com   
3      China        Beijing, China        http://www.cnpc.com.cn   
4      Japan         Toyota, Japan  http://www.toyota-global.com   
..       ...                   ...                           ...   
495   Israel  Petach Tikva, Israel      http://www.tevapharm.com   
496    China        Beijing, China   http://www.newchinalife.com   
497  Britain     Bradford, Britain      http://www.morrisons.com   
498  Germany      Hanover, Germany       http://www.tuigroup.com   
499      USA   Fort Lauderdale, FL     http://www.autonation.com   

     years_on_global_500_list  employees  total_stockholder_equity  
0                          23    2300000                     77798  
1                          17     926067                    209456  
2                          19     713288                    106523  
3                          17    1512048                    301893  
4                          23     364445                    157210  
..                        ...        ...                       ...  
495                         1      56960                     33337  
496                         2      54378                      8507  
497                        13      77210                      5111 

In [60]:
f500 = pd.read_csv("f500.csv", index_col = "company")

In [61]:
f500

rank  revenues  revenue_change  profits  \
company                                                                   
Walmart                            1    485873             0.8  13643.0   
State Grid                         2    315199            -4.4   9571.3   
Sinopec Group                      3    267518            -9.1   1257.9   
China National Petroleum           4    262573           -12.3   1867.5   
Toyota Motor                       5    254694             7.7  16899.3   
...                              ...       ...             ...      ...   
Teva Pharmaceutical Industries   496     21903            11.5    329.0   
New China Life Insurance         497     21796           -13.3    743.9   
Wm. Morrison Supermarkets        498     21741           -11.3    406.4   
TUI                              499     21655            -5.5   1151.7   
AutoNation                       500     21609             3.6    430.5   

                                assets  profit_change                  ceo  \
company                                                                      
Walmart                         198825           -7.2  C. Douglas McMillon   
State Grid                      489838           -6.2              Kou Wei   
Sinopec Group                   310726          -65.0            Wang Yupu   
China National Petroleum        585619          -73.7        Zhang Jianhua   
Toyota Motor                    437575          -12.3          Akio Toyoda   
...                                ...            ...                  ...   
Teva Pharmaceutical Industries   92890          -79.3    Yitzhak Peterburg   
New China Life Insurance        100609          -45.6             Wan Feng   
Wm. Morrison Supermarkets        11630           20.4       David T. Potts   
TUI                              16247          195.5    Friedrich Joussen   
AutoNation                       10060           -2.7   Michael J. Jackson   

                                                       industry  \
company                                                           
Walmart                                   General Merchandisers   
State Grid                                            Utilities   
Sinopec Group                                Petroleum Refining   
China National Petroleum                     Petroleum Refining   
Toyota Motor                           Motor Vehicles and Parts   
...                                                         ...   
Teva Pharmaceutical Industries                  Pharmaceuticals   
New China Life Insurance        Insurance: Life, Health (stock)   
Wm. Morrison Supermarkets                  Food and Drug Stores   
TUI                                             Travel Services   
AutoNation                                  Specialty Retailers   

                                                sector  previous_rank  \
company                                                                 
Walmart                                      Retailing              1   
State Grid                                      Energy              2   
Sinopec Group                                   Energy              4   
China National Petroleum                        Energy              3   
Toyota Motor                    Motor Vehicles & Parts              8   
...                                                ...            ...   
Teva Pharmaceutical Industries             Health Care              0   
New China Life Insurance                    Financials            427   
Wm. Morrison Supermarkets           Food & Drug Stores            437   
TUI                                  Business Services            467   
AutoNation                                   Retailing              0   

                                country           hq_location  \
company                                                         
Walmart                             USA       Bentonville, AR   
State Grid              

In [62]:
f500.index.name = None

In [63]:
f500

rank  revenues  revenue_change  profits  \
Walmart                            1    485873             0.8  13643.0   
State Grid                         2    315199            -4.4   9571.3   
Sinopec Group                      3    267518            -9.1   1257.9   
China National Petroleum           4    262573           -12.3   1867.5   
Toyota Motor                       5    254694             7.7  16899.3   
...                              ...       ...             ...      ...   
Teva Pharmaceutical Industries   496     21903            11.5    329.0   
New China Life Insurance         497     21796           -13.3    743.9   
Wm. Morrison Supermarkets        498     21741           -11.3    406.4   
TUI                              499     21655            -5.5   1151.7   
AutoNation                       500     21609             3.6    430.5   

                                assets  profit_change                  ceo  \
Walmart                         198825           -7.2  C. Douglas McMillon   
State Grid                      489838           -6.2              Kou Wei   
Sinopec Group                   310726          -65.0            Wang Yupu   
China National Petroleum        585619          -73.7        Zhang Jianhua   
Toyota Motor                    437575          -12.3          Akio Toyoda   
...                                ...            ...                  ...   
Teva Pharmaceutical Industries   92890          -79.3    Yitzhak Peterburg   
New China Life Insurance        100609          -45.6             Wan Feng   
Wm. Morrison Supermarkets        11630           20.4       David T. Potts   
TUI                              16247          195.5    Friedrich Joussen   
AutoNation                       10060           -2.7   Michael J. Jackson   

                                                       industry  \
Walmart                                   General Merchandisers   
State Grid                                            Utilities   
Sinopec Group                                Petroleum Refining   
China National Petroleum                     Petroleum Refining   
Toyota Motor                           Motor Vehicles and Parts   
...                                                         ...   
Teva Pharmaceutical Industries                  Pharmaceuticals   
New China Life Insurance        Insurance: Life, Health (stock)   
Wm. Morrison Supermarkets                  Food and Drug Stores   
TUI                                             Travel Services   
AutoNation                                  Specialty Retailers   

                                                sector  previous_rank  \
Walmart                                      Retailing              1   
State Grid                                      Energy              2   
Sinopec Group                                   Energy              4   
China National Petroleum                        Energy              3   
Toyota Motor                    Motor Vehicles & Parts              8   
...                                                ...            ...   
Teva Pharmaceutical Industries             Health Care              0   
New China Life Insurance                    Financials            427   
Wm. Morrison Supermarkets           Food & Drug Stores            437   
TUI                                  Business Services            467   
AutoNation                                   Retailing              0   

                                country           hq_location  \
Walmart                             USA       Bentonville, AR   
State Grid                        China        Beijing, China   
Sinopec Group                     China        Beijing, China   
China National Petroleum          China        Beijing, China   
Toyota Motor                      Japan         Toyota, Japan   
...                                 ...                   ...   
Teva Pharmaceutical Industries   Israel  Petach Tikva, Is

In [64]:
type(f500)

pandas.core.frame.DataFrame

In [65]:
f500.head()

rank  revenues  revenue_change  profits  assets  \
Walmart                      1    485873             0.8  13643.0  198825   
State Grid                   2    315199            -4.4   9571.3  489838   
Sinopec Group                3    267518            -9.1   1257.9  310726   
China National Petroleum     4    262573           -12.3   1867.5  585619   
Toyota Motor                 5    254694             7.7  16899.3  437575   

                          profit_change                  ceo  \
Walmart                            -7.2  C. Douglas McMillon   
State Grid                         -6.2              Kou Wei   
Sinopec Group                     -65.0            Wang Yupu   
China National Petroleum          -73.7        Zhang Jianhua   
Toyota Motor                      -12.3          Akio Toyoda   

                                          industry                  sector  \
Walmart                      General Merchandisers               Retailing   
State Grid                               Utilities                  Energy   
Sinopec Group                   Petroleum Refining                  Energy   
China National Petroleum        Petroleum Refining                  Energy   
Toyota Motor              Motor Vehicles and Parts  Motor Vehicles & Parts   

                          previous_rank country      hq_location  \
Walmart                               1     USA  Bentonville, AR   
State Grid                            2   China   Beijing, China   
Sinopec Group                         4   China   Beijing, China   
China National Petroleum              3   China   Beijing, China   
Toyota Motor                          8   Japan    Toyota, Japan   

                                               website  \
Walmart                         http://www.walmart.com   
State Grid                      http://www.sgcc.com.cn   
Sinopec Group                   http://www.sinopec.com   
China National Petroleum        http://www.cnpc.com.cn   
Toyota Motor              http://www.toyota-global.com   

                          years_on_global_500_list  employees  \
Walmart                                         23    2300000   
State Grid                                      17     926067   
Sinopec Group                                   19     713288   
China National Petroleum                        17    1512048   
Toyota Motor                                    23     364445   

                          total_stockholder_equity  
Walmart                                      77798  
State Grid                                  209456  
Sinopec Group                               106523  
China National Petroleum                    301893  
Toyota Motor                                157210

In [66]:
f500.head(2)

rank  revenues  revenue_change  profits  assets  profit_change  \
Walmart        1    485873             0.8  13643.0  198825           -7.2   
State Grid     2    315199            -4.4   9571.3  489838           -6.2   

                            ceo               industry     sector  \
Walmart     C. Douglas McMillon  General Merchandisers  Retailing   
State Grid              Kou Wei              Utilities     Energy   

            previous_rank country      hq_location                 website  \
Walmart                 1     USA  Bentonville, AR  http://www.walmart.com   
State Grid              2   China   Beijing, China  http://www.sgcc.com.cn   

            years_on_global_500_list  employees  total_stockholder_equity  
Walmart                           23    2300000                     77798  
State Grid                        17     926067                    209456

In [68]:
f500.tail()

rank  revenues  revenue_change  profits  \
Teva Pharmaceutical Industries   496     21903            11.5    329.0   
New China Life Insurance         497     21796           -13.3    743.9   
Wm. Morrison Supermarkets        498     21741           -11.3    406.4   
TUI                              499     21655            -5.5   1151.7   
AutoNation                       500     21609             3.6    430.5   

                                assets  profit_change                 ceo  \
Teva Pharmaceutical Industries   92890          -79.3   Yitzhak Peterburg   
New China Life Insurance        100609          -45.6            Wan Feng   
Wm. Morrison Supermarkets        11630           20.4      David T. Potts   
TUI                              16247          195.5   Friedrich Joussen   
AutoNation                       10060           -2.7  Michael J. Jackson   

                                                       industry  \
Teva Pharmaceutical Industries                  Pharmaceuticals   
New China Life Insurance        Insurance: Life, Health (stock)   
Wm. Morrison Supermarkets                  Food and Drug Stores   
TUI                                             Travel Services   
AutoNation                                  Specialty Retailers   

                                            sector  previous_rank  country  \
Teva Pharmaceutical Industries         Health Care              0   Israel   
New China Life Insurance                Financials            427    China   
Wm. Morrison Supermarkets       Food & Drug Stores            437  Britain   
TUI                              Business Services            467  Germany   
AutoNation                               Retailing              0      USA   

                                         hq_location  \
Teva Pharmaceutical Industries  Petach Tikva, Israel   
New China Life Insurance              Beijing, China   
Wm. Morrison Supermarkets          Bradford, Britain   
TUI                                 Hanover, Germany   
AutoNation                       Fort Lauderdale, FL   

                                                    website  \
Teva Pharmaceutical Industries     http://www.tevapharm.com   
New China Life Insurance        http://www.newchinalife.com   
Wm. Morrison Supermarkets          http://www.morrisons.com   
TUI                                 http://www.tuigroup.com   
AutoNation                        http://www.autonation.com   

                                years_on_global_500_list  employees  \
Teva Pharmaceutical Industries                         1      56960   
New China Life Insurance                               2      54378   
Wm. Morrison Supermarkets                             13      77210   
TUI                                                   23      66779   
AutoNation                                            12      26000   

                                total_stockholder_equity  
Teva Pharmaceutical Industries                     33337  
New China Life Insurance                            8507  
Wm. Morrison Supermarkets                           5111  
TUI                                                 3006  
AutoNation                                          2310

In [69]:
f500.tail(2)

rank  revenues  revenue_change  profits  assets  profit_change  \
TUI          499     21655            -5.5   1151.7   16247          195.5   
AutoNation   500     21609             3.6    430.5   10060           -2.7   

                           ceo             industry             sector  \
TUI          Friedrich Joussen      Travel Services  Business Services   
AutoNation  Michael J. Jackson  Specialty Retailers          Retailing   

            previous_rank  country          hq_location  \
TUI                   467  Germany     Hanover, Germany   
AutoNation              0      USA  Fort Lauderdale, FL   

                              website  years_on_global_500_list  employees  \
TUI           http://www.tuigroup.com                        23      66779   
AutoNation  http://www.autonation.com                        12      26000   

            total_stockholder_equity  
TUI                             3006  
AutoNation                      2310

In [70]:
f500.dtypes

rank                          int64
revenues                      int64
revenue_change              float64
profits                     float64
assets                        int64
profit_change               float64
ceo                          object
industry                     object
sector                       object
previous_rank                 int64
country                      object
hq_location                  object
website                      object
years_on_global_500_list      int64
employees                     int64
total_stockholder_equity      int64
dtype: object

In [71]:
f500.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   rank                      500 non-null    int64  
 1   revenues                  500 non-null    int64  
 2   revenue_change            498 non-null    float64
 3   profits                   499 non-null    float64
 4   assets                    500 non-null    int64  
 5   profit_change             436 non-null    float64
 6   ceo                       500 non-null    object 
 7   industry                  500 non-null    object 
 8   sector                    500 non-null    object 
 9   previous_rank             500 non-null    int64  
 10  country                   500 non-null    object 
 11  hq_location               500 non-null    object 
 12  website                   500 non-null    object 
 13  years_on_global_500_list  500 non-null    int64  
 14  em

In [72]:
66.4/1024

0.06484375

In [75]:
(500*17*8)/1024

66.40625

In [76]:
f500.loc["TUI"]

rank                                            499
revenues                                      21655
revenue_change                                 -5.5
profits                                      1151.7
assets                                        16247
profit_change                                 195.5
ceo                               Friedrich Joussen
industry                            Travel Services
sector                            Business Services
previous_rank                                   467
country                                     Germany
hq_location                        Hanover, Germany
website                     http://www.tuigroup.com
years_on_global_500_list                         23
employees                                     66779
total_stockholder_equity                       3006
Name: TUI, dtype: object

In [77]:
f500.iloc[499]

rank                                              500
revenues                                        21609
revenue_change                                    3.6
profits                                         430.5
assets                                          10060
profit_change                                    -2.7
ceo                                Michael J. Jackson
industry                          Specialty Retailers
sector                                      Retailing
previous_rank                                       0
country                                           USA
hq_location                       Fort Lauderdale, FL
website                     http://www.autonation.com
years_on_global_500_list                           12
employees                                       26000
total_stockholder_equity                         2310
Name: AutoNation, dtype: object

In [78]:
#  API